//
// GetHealth429Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetHealth429Response: Codable {
    public var error: ModelError?
    public var meta: Meta?
    public var success: Bool

    public init(error: ModelError? = nil, meta: Meta? = nil, success: Bool) {
        self.error = error
        self.meta = meta
        self.success = success
    }
}
