//
// GetV1RunnerModels200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetV1RunnerModels200ResponseData: Codable {
    public var models: [String]?

    public init(models: [String]? = nil) {
        self.models = models
    }
}
