//
// Meta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Meta: Codable {
    public var duration: String?
    public var page: Int?
    public var perPage: Int?
    public var requestId: String?
    public var total: Int?

    public init(duration: String? = nil, page: Int? = nil, perPage: Int? = nil, requestId: String? = nil, total: Int? = nil) {
        self.duration = duration
        self.page = page
        self.perPage = perPage
        self.requestId = requestId
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duration
        case page
        case perPage = "per_page"
        case requestId = "request_id"
        case total
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        duration = try container.decodeIfPresent(String.self, forKey: .duration)
        page = try container.decodeIfPresent(Int.self, forKey: .page)
        perPage = try container.decodeIfPresent(Int.self, forKey: .perPage)
        requestId = try container.decodeIfPresent(String.self, forKey: .requestId)
        total = try container.decodeIfPresent(Int.self, forKey: .total)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(page, forKey: .page)
        try container.encodeIfPresent(perPage, forKey: .perPage)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(total, forKey: .total)
    }
}
