//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelError: Codable {
    public var code: String
    public var details: Any?
    public var message: String

    public init(code: String, details: Any? = nil, message: String) {
        self.code = code
        self.details = details
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case details
        case message
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        code = try container.decode(String.self, forKey: .code)
        details = try container.decodeIfPresent(Any.self, forKey: .details)
        message = try container.decode(String.self, forKey: .message)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        if let details = details {
            try container.encodeIfPresent(try JSONSerialization.data(withJSONObject: details), forKey: .details)
        }
        try container.encode(message, forKey: .message)
    }
}
