//
// PostV1RunnerChatRequestMessagesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostV1RunnerChatRequestMessagesInner: Codable {
    public var content: String
    public var role: String

    public init(content: String, role: String) {
        self.content = content
        self.role = role
    }
}
