//
// PostV1RunnerChat200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostV1RunnerChat200ResponseData: Codable {
    public var reply: String?

    public init(reply: String? = nil) {
        self.reply = reply
    }
}
