//
// PostV1RunnerGenerateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostV1RunnerGenerateRequest: Codable {
    public var prompt: String

    public init(prompt: String) {
        self.prompt = prompt
    }
}
