//
// PostV1RunnerChatRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostV1RunnerChatRequest: Codable {
    public var messages: [PostV1RunnerChatRequestMessagesInner]

    public init(messages: [PostV1RunnerChatRequestMessagesInner]) {
        self.messages = messages
    }
}
