//
// PostV1RunnerChat200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PostV1RunnerChat200Response: Codable {
    public var data: PostV1RunnerChat200ResponseData?
    public var error: ModelError?
    public var meta: Meta?
    public var success: Bool

    public init(data: PostV1RunnerChat200ResponseData? = nil, error: ModelError? = nil, meta: Meta? = nil, success: Bool) {
        self.data = data
        self.error = error
        self.meta = meta
        self.success = success
    }
}
