//
// Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Response: Codable {
    public var data: Any?
    public var error: ModelError?
    public var meta: Meta?
    public var success: Bool

    public init(data: Any? = nil, error: ModelError? = nil, meta: Meta? = nil, success: Bool) {
        self.data = data
        self.error = error
        self.meta = meta
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case error
        case meta
        case success
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        data = try container.decodeIfPresent(Any.self, forKey: .data)
        error = try container.decodeIfPresent(ModelError.self, forKey: .error)
        meta = try container.decodeIfPresent(Meta.self, forKey: .meta)
        success = try container.decode(Bool.self, forKey: .success)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let data = data {
            try container.encodeIfPresent(try JSONSerialization.data(withJSONObject: data), forKey: .data)
        }
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encode(success, forKey: .success)
    }
}
