//
// RunnerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import Combine
import OpenAPITransport


open class RunnerAPI {
    private let transport: OpenAPITransport
    public var encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(OpenISO8601DateFormatter())
        return encoder
    }()
    public var decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(OpenISO8601DateFormatter())
        return decoder
    }()
    public var baseURL = URL(string: "http://localhost")

    public init(_ transport: OpenAPITransport) {
        self.transport = transport
    }

    public enum GetV1RunnerModelsError: Error, CustomStringConvertible {
        // Bad request
        case code400Error(GetHealth429Response)
        // Unauthorised
        case code401Error(GetHealth429Response)
        // Forbidden
        case code403Error(GetHealth429Response)
        // Too many requests
        case code429Error(GetHealth429Response)
        // Internal server error
        case code500Error(GetHealth429Response)
        // Gateway timeout
        case code504Error(GetHealth429Response)

        public var description: String {
            switch self {
            case .code400Error(let object):
                return "GetV1RunnerModelsError: Bad request: \(object)"
            case .code401Error(let object):
                return "GetV1RunnerModelsError: Unauthorised: \(object)"
            case .code403Error(let object):
                return "GetV1RunnerModelsError: Forbidden: \(object)"
            case .code429Error(let object):
                return "GetV1RunnerModelsError: Too many requests: \(object)"
            case .code500Error(let object):
                return "GetV1RunnerModelsError: Internal server error: \(object)"
            case .code504Error(let object):
                return "GetV1RunnerModelsError: Gateway timeout: \(object)"
            }
        }
    }

    /// List configured runner model routes
    /// - GET /v1/runner/models
    /// - 
    /// - :
    /// - type: http
    /// - name: bearerAuth
    /// - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
    /// - returns: AnyPublisher<GetV1RunnerModels200Response, Error> 
    open func getV1RunnerModels() -> AnyPublisher<GetV1RunnerModels200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/v1/runner/models"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<GetV1RunnerModels200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code400Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 403 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code403Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 429 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code429Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 500 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code500Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 504 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetV1RunnerModelsError.code504Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(GetV1RunnerModels200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum PostV1RunnerChatError: Error, CustomStringConvertible {
        // Bad request
        case code400Error(GetHealth429Response)
        // Unauthorised
        case code401Error(GetHealth429Response)
        // Forbidden
        case code403Error(GetHealth429Response)
        // Too many requests
        case code429Error(GetHealth429Response)
        // Internal server error
        case code500Error(GetHealth429Response)
        // Gateway timeout
        case code504Error(GetHealth429Response)

        public var description: String {
            switch self {
            case .code400Error(let object):
                return "PostV1RunnerChatError: Bad request: \(object)"
            case .code401Error(let object):
                return "PostV1RunnerChatError: Unauthorised: \(object)"
            case .code403Error(let object):
                return "PostV1RunnerChatError: Forbidden: \(object)"
            case .code429Error(let object):
                return "PostV1RunnerChatError: Too many requests: \(object)"
            case .code500Error(let object):
                return "PostV1RunnerChatError: Internal server error: \(object)"
            case .code504Error(let object):
                return "PostV1RunnerChatError: Gateway timeout: \(object)"
            }
        }
    }

    /// Multi-turn chat completion
    /// - POST /v1/runner/chat
    /// - 
    /// - :
    /// - type: http
    /// - name: bearerAuth
    /// - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
    /// - parameter postV1RunnerChatRequest: (body)  
    /// - returns: AnyPublisher<PostV1RunnerChat200Response, Error> 
    open func postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest) -> AnyPublisher<PostV1RunnerChat200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/v1/runner/chat"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                request.httpBody = try self.encoder.encode(postV1RunnerChatRequest)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<PostV1RunnerChat200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code400Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 403 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code403Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 429 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code429Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 500 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code500Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 504 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerChatError.code504Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(PostV1RunnerChat200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum PostV1RunnerGenerateError: Error, CustomStringConvertible {
        // Bad request
        case code400Error(GetHealth429Response)
        // Unauthorised
        case code401Error(GetHealth429Response)
        // Forbidden
        case code403Error(GetHealth429Response)
        // Too many requests
        case code429Error(GetHealth429Response)
        // Internal server error
        case code500Error(GetHealth429Response)
        // Gateway timeout
        case code504Error(GetHealth429Response)

        public var description: String {
            switch self {
            case .code400Error(let object):
                return "PostV1RunnerGenerateError: Bad request: \(object)"
            case .code401Error(let object):
                return "PostV1RunnerGenerateError: Unauthorised: \(object)"
            case .code403Error(let object):
                return "PostV1RunnerGenerateError: Forbidden: \(object)"
            case .code429Error(let object):
                return "PostV1RunnerGenerateError: Too many requests: \(object)"
            case .code500Error(let object):
                return "PostV1RunnerGenerateError: Internal server error: \(object)"
            case .code504Error(let object):
                return "PostV1RunnerGenerateError: Gateway timeout: \(object)"
            }
        }
    }

    /// Single-prompt generation
    /// - POST /v1/runner/generate
    /// - 
    /// - :
    /// - type: http
    /// - name: bearerAuth
    /// - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
    /// - parameter postV1RunnerGenerateRequest: (body)  
    /// - returns: AnyPublisher<PostV1RunnerChat200Response, Error> 
    open func postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest) -> AnyPublisher<PostV1RunnerChat200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/v1/runner/generate"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                request.httpBody = try self.encoder.encode(postV1RunnerGenerateRequest)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<PostV1RunnerChat200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code400Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 403 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code403Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 429 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code429Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 500 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code500Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 504 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return PostV1RunnerGenerateError.code504Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(PostV1RunnerChat200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }
}
