//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import Combine
import OpenAPITransport


open class SystemAPI {
    private let transport: OpenAPITransport
    public var encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(OpenISO8601DateFormatter())
        return encoder
    }()
    public var decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(OpenISO8601DateFormatter())
        return decoder
    }()
    public var baseURL = URL(string: "http://localhost")

    public init(_ transport: OpenAPITransport) {
        self.transport = transport
    }

    public enum GetHealthError: Error, CustomStringConvertible {
        // Too many requests
        case code429Error(GetHealth429Response)
        // Internal server error
        case code500Error(GetHealth429Response)
        // Gateway timeout
        case code504Error(GetHealth429Response)

        public var description: String {
            switch self {
            case .code429Error(let object):
                return "GetHealthError: Too many requests: \(object)"
            case .code500Error(let object):
                return "GetHealthError: Internal server error: \(object)"
            case .code504Error(let object):
                return "GetHealthError: Gateway timeout: \(object)"
            }
        }
    }

    /// Health check
    /// - GET /health
    /// - Returns server health status
    /// - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
    /// - returns: AnyPublisher<GetHealth200Response, Error> 
    open func getHealth() -> AnyPublisher<GetHealth200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/health"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<GetHealth200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 429 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetHealthError.code429Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 500 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetHealthError.code500Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 504 {
                        do {
                            let error = try self.decoder.decode(GetHealth429Response.self, from: transportError.data)
                            return GetHealthError.code504Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(GetHealth200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }
}
